# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=25)),
                ('apellido1', models.CharField(default=b'', max_length=100)),
                ('apellido2', models.CharField(blank=True, default=b'', max_length=100, null=True)),
                ('telefono1', models.CharField(default=b'', max_length=9)),
                ('telefono2', models.CharField(blank=True, default=b'', max_length=9, null=True)),
                ('email', models.EmailField(blank=True, default=b'', max_length=254, null=True)),
                ('cuenta_bancaria', models.CharField(default=b'', max_length=25)),
                ('localidad', models.CharField(default=b'', max_length=25)),
                ('cp', models.CharField(default=b'48980', max_length=5)),
                ('dni', models.CharField(blank=True, default=b'', max_length=9, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(default=b'20XX-XX', max_length=8)),
                ('activo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('factura', models.BooleanField(default=False)),
                ('metalico', models.BooleanField(default=True)),
                ('precio', models.FloatField(default=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Alumno')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name=b'Nombre')),
                ('aforo', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pdi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.DecimalField(choices=[(1, 'Festivo'), (2, 'Inicio Curso'), (3, 'Fin Curso'), (4, 'Inicio vacaciones/puente'), (5, 'Fin vacaciones/puente')], decimal_places=0, max_digits=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gestioneide.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=25)),
                ('precio', models.FloatField(default=100)),
                ('examen', models.CharField(blank=True, default=b'', max_length=25, null=True)),
                ('nivel', models.CharField(blank=True, default=b'', max_length=25, null=True)),
                ('nota_aprobado', models.FloatField(default=50)),
                ('solo_examen_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=1)),
                ('justificadas', models.DecimalField(decimal_places=0, default=b'0', max_digits=3)),
                ('faltas', models.DecimalField(decimal_places=0, default=b'0', max_digits=3)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anotacion', models.CharField(default=b'', max_length=25)),
                ('tipo', models.DecimalField(choices=[(1, 'Festivo'), (2, 'Inicio Curso'), (3, 'Fin Curso'), (4, 'Inicio vacaciones/Puente'), (5, 'Fin Vacaciones/Puente'), (6, 'Festivo oficial')], decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=25)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('num_max', models.DecimalField(decimal_places=0, default=14, max_digits=2)),
                ('menores', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Curso')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(default=b'', max_length=25)),
                ('anotacion', models.CharField(default=b'', max_length=25)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=b'', max_length=50)),
                ('autor', models.CharField(default=b'', max_length=25)),
                ('isbn', models.CharField(default=b'', max_length=40)),
                ('editorial', models.CharField(default=b'', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.DecimalField(decimal_places=0, max_digits=1)),
                ('grama', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('grama_baremo', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('expresion', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('expresion_baremo', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('lectura', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('lectura_baremo', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=25)),
                ('apellido', models.CharField(default=b'', max_length=50)),
                ('telefono', models.CharField(default=b'', max_length=9)),
                ('email', models.EmailField(blank=True, default=b'', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('mes', models.DecimalField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], decimal_places=0, max_digits=1)),
                ('medio_mes', models.BooleanField(default=False)),
                ('grupos', models.ManyToManyField(to='gestioneide.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='libros',
            field=models.ManyToManyField(to='gestioneide.Libro'),
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gestioneide.Grupo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gestioneide.Profesor'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Grupo'),
        ),
    ]
