# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0004_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivo',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Year'),
        ),
        migrations.DeleteModel(
            name='Ano',
        ),
    ]
