# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0005_auto_20160314_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='ano',
            new_name='year',
        ),
    ]
