# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0006_auto_20160314_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='precio',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(default=b'201X-1X', max_length=8),
        ),
    ]
