# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0007_auto_20160319_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
