# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0008_auto_20160319_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default=b'', max_length=25),
        ),
    ]
