# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0009_alumno_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
