# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0010_auto_20160406_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='localidad',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
