# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0011_auto_20160406_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='observaciones',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True),
        ),
    ]
