# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0013_auto_20160409_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='expresion',
            new_name='control',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='expresion_baremo',
            new_name='grammar',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='grama',
            new_name='listenning',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='grama_baremo',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='lectura',
            new_name='speaking',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='lectura_baremo',
            new_name='useofenglish',
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_evaluacion',
            field=models.DecimalField(choices=[(1, 'Todo'), (2, 'solo algo'), (3, 'peques')], decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='comportamiento',
            field=models.CharField(default=b'B', max_length=2),
        ),
        migrations.AddField(
            model_name='nota',
            name='comportamiento_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='comportamiento_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='control_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='control_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='grammar_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='grammar_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='listenning_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='listenning_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='reading_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='reading_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='speaking_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='speaking_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='useofenglish_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='useofenglish_np',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='writing',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='nota',
            name='writing_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota',
            name='writing_np',
            field=models.BooleanField(default=False),
        ),
    ]
