# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0014_auto_20160411_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_evaluacion',
            field=models.DecimalField(choices=[(1, 'Otro'), (2, 'elementary_intermediate'), (3, 'upper_proficiency')], decimal_places=0, max_digits=1),
        ),
    ]
