# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0018_auto_20160415_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festivo',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='festivo',
            name='tipo',
            field=models.DecimalField(choices=[(1, 'Festivo'), (2, 'Inicio Curso'), (3, 'Fin Curso'), (4, 'Inicio vacaciones/Puente'), (5, 'Fin Vacaciones/Puente'), (6, 'Festivo oficial'), (7, 'Inicio trimestre'), (8, 'Fin trimestre')], decimal_places=0, max_digits=1),
        ),
    ]
