# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0019_auto_20160517_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivo',
            name='anotacion',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
