# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0020_auto_20160523_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='fichero_csb19',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(blank=True, default=b'Santurtzi', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cuenta_bancaria',
            field=models.CharField(default=b'', max_length=23),
        ),
        migrations.AlterField(
            model_name='curso',
            name='libros',
            field=models.ManyToManyField(blank=True, to='gestioneide.Libro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='gestioneide.Grupo'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='mes',
            field=models.DecimalField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], decimal_places=0, max_digits=2),
        ),
    ]
