# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioneide', '0020_auto_20160523_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(blank=True, default=b'Santurtzi', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cuenta_bancaria',
            field=models.CharField(default=b'', max_length=23),
        ),
        migrations.AlterField(
            model_name='curso',
            name='libros',
            field=models.ManyToManyField(blank=True, to='gestioneide.Libro'),
        ),
    ]
