# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0021_auto_20160821_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='grupos_sueltos',
            field=models.BooleanField(default=False),
        ),
    ]
