# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0023_profesor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2)),
                ('dia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Presencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2)),
                ('dia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
        migrations.RemoveField(
            model_name='falta',
            name='faltas',
        ),
        migrations.RemoveField(
            model_name='falta',
            name='justificadas',
        ),
        migrations.AddField(
            model_name='falta',
            name='dia',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='falta',
            name='mes',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
