# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0024_auto_20160911_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurismoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TurismoAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.TurismoAsignatura')),
            ],
        ),
        migrations.CreateModel(
            name='TurismoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.DecimalField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes')], decimal_places=0, max_digits=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_turismo', to='gestioneide.TurismoAsignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_turismo', to='gestioneide.Aula')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_turismo', to='gestioneide.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='TurismoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=b'', max_length=50)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Year')),
            ],
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='metalico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turismoasignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.TurismoCurso'),
        ),
        migrations.AddField(
            model_name='turismoasignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Profesor'),
        ),
    ]
