# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0025_auto_20160919_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='errores',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='recibo',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='turismoasignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='gestioneide.TurismoCurso'),
        ),
    ]
