# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0027_auto_20161009_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='metalicos',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4),
        ),
    ]
