# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0028_recibo_metalicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 10, 16, 9, 5, 41, 390647, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
