# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-20 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioneide', '0031_anotacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='creador',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='texto',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
