# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0032_auto_20161020_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacion',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='comportamiento_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='control_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='grammar_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='listenning_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='reading_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='speaking_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='useofenglish_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='writing_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
    ]
