# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0033_auto_20161116_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCautrimestral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.DecimalField(decimal_places=0, max_digits=1)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('grammar', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('grammar_np', models.BooleanField(default=False, verbose_name=b'NP')),
                ('reading', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('reading_np', models.BooleanField(default=False, verbose_name=b'NP')),
                ('writing', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('writing_np', models.BooleanField(default=False, verbose_name=b'NP')),
                ('useofenglish', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('useofenglish_np', models.BooleanField(default=False, verbose_name=b'NP')),
                ('listenning', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('listenning_np', models.BooleanField(default=False, verbose_name=b'NP')),
                ('speaking', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('speaking_np', models.BooleanField(default=False, verbose_name=b'NP')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='NotaTrimestral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.DecimalField(decimal_places=0, max_digits=1)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('nota', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_evaluacion',
            field=models.DecimalField(choices=[(1, 'Otro'), (2, 'elementary_preintermediate'), (3, 'intermediate'), (4, 'prefirst_proficiency')], decimal_places=0, max_digits=1),
        ),
    ]
