# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0034_auto_20161211_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotaCautrimestral',
            new_name='NotaCuatrimestral',
        ),
    ]
