# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0035_auto_20161211_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacuatrimestral',
            name='reading_writing',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notacuatrimestral',
            name='reading_writing_np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
    ]
