# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0037_auto_20161213_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('resultado', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('observaciones', models.TextField(default=b'', max_length=350)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Alumno')),
                ('nivel_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Curso')),
            ],
        ),
    ]
