# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0039_auto_20170213_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCambridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DecimalField(decimal_places=0, default=2016, max_digits=4)),
                ('resultado', models.DecimalField(choices=[(1, 'A: Sobresaliente'), (2, 'B: Notable'), (3, 'C: Aprobado'), (4, 'D: Suspendido')], decimal_places=0, default=1, max_digits=2)),
                ('observaciones', models.TextField(default=b'', max_length=350)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Alumno')),
            ],
        ),
    ]
