# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0039_auto_20170213_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacuatrimestral',
            name='observaciones',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True),
        ),
    ]
