# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0041_resultadocambridge_nivel'),
        ('gestioneide', '0040_notacuatrimestral_observaciones'),
    ]

    operations = [
    ]
