# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0042_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='notatrimestral',
            name='np',
            field=models.BooleanField(default=False, verbose_name=b'NP'),
        ),
    ]
