# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0044_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='borrada',
            field=models.BooleanField(default=False),
        ),
    ]
