# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0046_auto_20170728_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurismoFalta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2)),
                ('dia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.TurismoAsistencia')),
            ],
        ),
        migrations.CreateModel(
            name='TurismoJustificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2)),
                ('dia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.TurismoAsistencia')),
            ],
        ),
        migrations.CreateModel(
            name='TurismoPresencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2)),
                ('dia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.TurismoAsistencia')),
            ],
        ),
    ]
