# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0048_auto_20180317_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name=b'Nombre')),
                ('telefono', models.CharField(default=b'', max_length=9)),
                ('email', models.EmailField(blank=True, default=b'', max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, default=b'', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.DecimalField(decimal_places=0, default=2095, max_digits=4)),
                ('oficina', models.DecimalField(decimal_places=0, default=363, max_digits=4)),
                ('dc', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cuenta', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name=b'Nombre')),
                ('telefono', models.CharField(default=b'', max_length=9)),
                ('email', models.EmailField(blank=True, default=b'', max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, default=b'', max_length=250, null=True)),
                ('razon_social', models.CharField(default=b'ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name=b'Nombre')),
                ('csb19_suffijo', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.CuentaBancaria')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Empresa'),
        ),
        migrations.AddField(
            model_name='aula',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Centro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Centro'),
        ),
    ]
