# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0049_auto_20180514_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='nombre',
            field=models.CharField(default=1, max_length=50, verbose_name=b'Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.CuentaBancaria'),
        ),
    ]
