# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0049_auto_20180516_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cif',
            field=models.CharField(default=b'B12345678', max_length=9),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(default=b'ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name=b'Raz\xc3\xb3n Social'),
        ),
    ]
