# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0050_auto_20180915_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Empresa'),
        ),
    ]
