# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-11 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0053_gruponotasparciales_notaparcial'),
        ('gestioneide', '0053_auto_20180926_1552'),
    ]

    operations = [
    ]
