# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0055_auto_20190605_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ano_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Year'),
        ),
    ]
