# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0056_auto_20190605_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(blank=True, default='Santurtzi', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cp',
            field=models.CharField(default='48980', max_length=5),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cuenta_bancaria',
            field=models.CharField(default='', max_length=23),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono1',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono2',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='texto',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='centro',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='centro',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='telefono',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='oficina',
            field=models.DecimalField(decimal_places=0, default='0553', max_digits=4),
        ),
        migrations.AlterField(
            model_name='curso',
            name='examen',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(default='B12345678', max_length=9),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(default='ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='festivo',
            name='anotacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='historia',
            name='anotacion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historia',
            name='tipo',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='comportamiento',
            field=models.CharField(default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='nota',
            name='comportamiento_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='control_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='grammar_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='listenning_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='reading_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='speaking_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='useofenglish_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='writing_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='grammar_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='listenning_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='reading_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='reading_writing_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='speaking_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='useofenglish_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notacuatrimestral',
            name='writing_np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='aspectos_mejorar',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Aspectos a mejorar'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='comp_escrita',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name='Comprensión Escrita'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='comp_oral',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name='Comprensión Oral'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='exp_escrita',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name='Expresión Escrita'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='exp_oral',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name='Expresión Oral'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='np',
            field=models.BooleanField(default=False, verbose_name='NP'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='temas_repasar',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Temas a repasar'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='pruebanivel',
            name='observaciones',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='errores',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fichero_csb19',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resultadocambridge',
            name='observaciones',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='turismoasignatura',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='turismocurso',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(default='201X-1X', max_length=8),
        ),
    ]
