# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0057_auto_20191123_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(default=b'ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name=b'Raz\xc3\xb3n Social'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='comp_escrita',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name=b'Comprensi\xc3\xb3n Escrita'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='comp_oral',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name=b'Comprensi\xc3\xb3n Oral'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='exp_escrita',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name=b'Expresi\xc3\xb3n Escrita'),
        ),
        migrations.AlterField(
            model_name='notatrimestral',
            name='exp_oral',
            field=models.DecimalField(blank=True, choices=[(0, 'No Aplica'), (1, 'Mejorable'), (2, 'Satisfactorio'), (3, 'Muy Satisfactorio')], decimal_places=0, default=0, max_digits=1, null=True, verbose_name=b'Expresi\xc3\xb3n Oral'),
        ),
    ]
