# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0058_auto_20191125_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono1',
            field=models.CharField(default=b'', max_length=12),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono2',
            field=models.CharField(blank=True, default=b'', max_length=12, null=True),
        ),
    ]
