# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0059_auto_20191125_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email2',
            field=models.EmailField(blank=True, default=b'', max_length=254, null=True),
        ),
    ]
