# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0061_auto_20200209_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacuatrimestral',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notatrimestral',
            name='email_enviados',
            field=models.BooleanField(default=False),
        ),
    ]
