# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-31 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0062_auto_20200228_1802'),
        ('gestioneide', '0062_auto_20200214_1642'),
    ]

    operations = [
    ]
