# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-03 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0063_merge_20200331_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre'], 'permissions': [('send_email', 'Send e-mail to group students'), ('view_data', 'View group data')]},
        ),
    ]
