# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-03 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0064_auto_20200403_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre'], 'permissions': [('send_email_grupo', 'Send e-mail to group students'), ('view_data_grupo', 'View group data')]},
        ),
    ]
