# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-16 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0066_anotaciongrupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotaciongrupo',
            old_name='alumno',
            new_name='grupo',
        ),
    ]
