# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0069_clase_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='listenning',
            new_name='listening',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='listenning_na',
            new_name='listening_na',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='listenning_np',
            new_name='listening_np',
        ),
        migrations.RenameField(
            model_name='notacuatrimestral',
            old_name='listenning',
            new_name='listening',
        ),
        migrations.RenameField(
            model_name='notacuatrimestral',
            old_name='listenning_np',
            new_name='listening_np',
        ),
    ]
