# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-07 19:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0071_auto_20210519_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='precio_matricula',
            field=models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=5),
        ),
    ]
