# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0072_centro_precio_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turismoasignatura',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='turismoasignatura',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='turismoasistencia',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='turismoasistencia',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='turismoclase',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='turismoclase',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='turismoclase',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='turismocurso',
            name='year',
        ),
        migrations.RemoveField(
            model_name='turismofalta',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='turismojustificada',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='turismopresencia',
            name='asistencia',
        ),
        migrations.DeleteModel(
            name='TurismoAsignatura',
        ),
        migrations.DeleteModel(
            name='TurismoAsistencia',
        ),
        migrations.DeleteModel(
            name='TurismoClase',
        ),
        migrations.DeleteModel(
            name='TurismoCurso',
        ),
        migrations.DeleteModel(
            name='TurismoFalta',
        ),
        migrations.DeleteModel(
            name='TurismoJustificada',
        ),
        migrations.DeleteModel(
            name='TurismoPresencia',
        ),
    ]
