# Generated by Django 2.2.24 on 2021-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0075_notaunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaunits',
            name='unit5',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit6',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
