# Generated by Django 2.2.24 on 2021-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0076_auto_20210908_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaunits',
            name='unit10',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit11',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit12',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit13',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit14',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit15',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit7',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit8',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='notaunits',
            name='unit9',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
