# Generated by Django 2.2.24 on 2021-09-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0077_auto_20210908_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaUnitsWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', models.DecimalField(decimal_places=0, max_digits=1)),
                ('unit1', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit2', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit3', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit4', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit5', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit6', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit7', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit8', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit9', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit10', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit11', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit12', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit13', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit14', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('unit15', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
            ],
        ),
    ]
