# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-14 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobetuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='desempleado',
            field=models.BooleanField(help_text='haga click en el check si se encuentra en situaci\xf3n de desempleo', verbose_name='Desempleado'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fecha_desempleo',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='titulacion',
            field=models.DecimalField(choices=[(1, 'Sin titulaci\xf3n'), (2, 'Graduado Escolar o ESO'), (3, 'Bachillerato, COU o similar'), (4, 'Grado, Licenciatura o Diplomatura'), (5, 'Certificado de Profesionalidad en Turismo y Hosteler\xeda de Nivel 1'), (6, 'Certificado de Profesionalidad en Turismo y Hosteler\xeda de Nivel 2 o 3'), (7, 'Ciclo Grado Medio, FPI, Certificado de Profesionalidad de Nivel 2 en otra especialidad'), (8, 'Ciclo de Grado Superior, FPII; Certificado de Profesionalidad de Nivel 3 en otra especialidad')], decimal_places=0, max_digits=1, verbose_name='Titulaci\xf3n (*)'),
        ),
    ]
