# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobetuz', '0003_auto_20190107_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('curso', models.CharField(choices=[(b'cocina', b'Cocina'), (b'ingles', b'Ingl\xc3\xa9s')], max_length=25, verbose_name='Elige un curso (*)')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre (*)')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s) (*)')),
                ('birth_date', models.DateField(help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', verbose_name='Fecha Nacimiento')),
                ('telephone', models.CharField(max_length=12, verbose_name=b'Tel\xc3\xa9fono (*)')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email (*)')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('accept_conditions', models.BooleanField(default=True, help_text='You must accept the conditions to register', verbose_name='Accept the conditions')),
            ],
        ),
        migrations.DeleteModel(
            name='Registration2019e',
        ),
        migrations.AlterField(
            model_name='registration',
            name='accept_conditions',
            field=models.BooleanField(default=True, verbose_name='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='desempleado',
            field=models.BooleanField(help_text='haga click en el check si se encuentra en situaci\xf3n de desempleo', verbose_name='Desempleado'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fecha_desempleo',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Formato: AAAA-MM-DD(a\xf1o-mes-d\xeda)', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='titulacion',
            field=models.DecimalField(choices=[(1, 'Sin titulaci\xf3n'), (2, 'Graduado Escolar o ESO'), (3, 'Bachillerato, COU o similar'), (4, 'Grado, Licenciatura o Diplomatura'), (5, 'Certificado de Profesionalidad en Turismo y Hosteler\xeda de Nivel 1'), (6, 'Certificado de Profesionalidad en Turismo y Hosteler\xeda de Nivel 2 o 3'), (7, 'Ciclo Grado Medio, FPI, Certificado de Profesionalidad de Nivel 2 en otra especialidad'), (8, 'Ciclo de Grado Superior, FPII; Certificado de Profesionalidad de Nivel 3 en otra especialidad')], decimal_places=0, max_digits=1, verbose_name='Titulaci\xf3n (*)'),
        ),
    ]
