# Generated by Django 2.2.24 on 2021-09-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobetuz', '0008_auto_20210618_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='accept_conditions',
            field=models.BooleanField(blank=True, default=True, verbose_name='Doy mi consentimiento expreso para recibir comunicaciones en los términos anteriormente descritos.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='curso',
            field=models.ForeignKey(limit_choices_to={'matricula_abierta': True}, on_delete=django.db.models.deletion.CASCADE, to='hobetuz.Curso', verbose_name='Primera Opción (*)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='curso2',
            field=models.ForeignKey(blank=True, limit_choices_to={'matricula_abierta': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration2_set', to='hobetuz.Curso', verbose_name='Segunda Opción'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='curso3',
            field=models.ForeignKey(blank=True, limit_choices_to={'matricula_abierta': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration3_set', to='hobetuz.Curso', verbose_name='Tercera Opción'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='curso4',
            field=models.ForeignKey(blank=True, limit_choices_to={'matricula_abierta': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration4_set', to='hobetuz.Curso', verbose_name='Cuarta Opción'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='curso5',
            field=models.ForeignKey(blank=True, limit_choices_to={'matricula_abierta': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration5_set', to='hobetuz.Curso', verbose_name='Quinta Opción'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email (*)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nivel_aleman',
            field=models.DecimalField(blank=True, choices=[(1, 'Cero'), (2, 'Inicial'), (3, 'Intermedio'), (4, 'Avanzado')], decimal_places=0, help_text='En caso de que haya escogido este idioma indique su nivel', max_digits=1, null=True, verbose_name='Nivel Aleman'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nivel_chino',
            field=models.DecimalField(blank=True, choices=[(1, 'Cero'), (2, 'Inicial'), (3, 'Intermedio'), (4, 'Avanzado')], decimal_places=0, help_text='En caso de que haya escogido este idioma indique su nivel', max_digits=1, null=True, verbose_name='Nivel Chino'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nivel_frances',
            field=models.DecimalField(blank=True, choices=[(1, 'Cero'), (2, 'Inicial'), (3, 'Intermedio'), (4, 'Avanzado')], decimal_places=0, help_text='En caso de que haya escogido este idioma indique su nivel', max_digits=1, null=True, verbose_name='Nivel Frances'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nivel_ingles',
            field=models.DecimalField(blank=True, choices=[(1, 'Cero'), (2, 'Inicial'), (3, 'Intermedio'), (4, 'Avanzado')], decimal_places=0, help_text='En caso de que haya escogido este idioma indique su nivel', max_digits=1, null=True, verbose_name='Nivel Ingles'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Tel. Fijo (*)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='telephone2',
            field=models.CharField(max_length=12, verbose_name='Tel. Móvil (*)'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='accept_conditions',
            field=models.BooleanField(blank=True, default=False, help_text='You must accept the conditions to register', verbose_name='Accept the conditions'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='curso',
            field=models.CharField(choices=[('cocina', 'Cocina'), ('ingles', 'Inglés')], max_length=25, verbose_name='Elige un curso (*)'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='desempleado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Estás desempleado/a'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email (*)'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='funcionario',
            field=models.BooleanField(blank=True, default=False, verbose_name='Eres funcionario/a'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='nivel_ingles',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='En caso de elegir ingles indicar el nivel'),
        ),
        migrations.AlterField(
            model_name='registration2019',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Teléfono (*)'),
        ),
    ]
