# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0065_auto_20200403_1657'),
        ('confirmaciones', '0002_auto_20200405_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='asistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
