# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmaciones', '0003_auto_20200405_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
