# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0065_auto_20200403_1657'),
        ('confirmaciones', '0004_auto_20200405_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='grupo',
            field=models.ForeignKey(default=816, on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Grupo'),
            preserve_default=False,
        ),
    ]
