# Generated by Django 2.2.24 on 2021-07-12 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbai_ticket',
            name='create_time',
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='DatosFactura_DescripcionFactura',
            field=models.CharField(default='Cursi Idiomas', max_length=255, verbose_name='Descripción Factura Social'),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='DatosFactura_ImporteTotalFactura',
            field=models.CharField(default='99999.99', max_length=8),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Destinatarios_ApellidosNombreRazonSocial',
            field=models.CharField(default='ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Destinatarios_NIF',
            field=models.CharField(default='B12345678', max_length=9),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Emisor_ApellidosNombreRazonSocial',
            field=models.CharField(default='ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Emisor_NIF',
            field=models.CharField(default='B12345678', max_length=9),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Factura_FechaExpedicionFactura',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Factura_HoraExpedicionFactura',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Factura_NumFactura',
            field=models.CharField(default='00001', max_length=5),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='Factura_SerieFactura',
            field=models.CharField(default='A2021', max_length=5),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='IDVersionTBAI',
            field=models.CharField(default='1.2', max_length=4),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='enviada',
            field=models.BooleanField(default=False),
        ),
    ]
