# Generated by Django 2.2.24 on 2021-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbai', '0002_auto_20210712_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Factura_FechaExpedicionFactura',
            field=models.DateField(auto_now_add=True),
        )
    ]
