# Generated by Django 2.2.24 on 2021-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbai', '0003_auto_20210712_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='DatosFactura_DescripcionFactura',
            field=models.CharField(default='Curso Idiomas', max_length=255, verbose_name='Descripción Factura'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='DatosFactura_ImporteTotalFactura',
            field=models.CharField(default='99999.99', max_length=8, verbose_name='Importe Total'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Destinatarios_ApellidosNombreRazonSocial',
            field=models.CharField(default='ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name='Razón Social Destinatario'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Destinatarios_NIF',
            field=models.CharField(default='B12345678', max_length=9, verbose_name='NIF Destinatario'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Emisor_ApellidosNombreRazonSocial',
            field=models.CharField(default='ESCUELAS INTERNACIONALES E.I.D.E.  S.L.', max_length=255, verbose_name='Razón Social Emisor'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Emisor_NIF',
            field=models.CharField(default='B12345678', max_length=9, verbose_name='NIF Emisor'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Factura_FechaExpedicionFactura',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Factura_HoraExpedicionFactura',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Factura_NumFactura',
            field=models.CharField(default='00001', max_length=5, verbose_name='Num. Factura'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Factura_SerieFactura',
            field=models.CharField(default='A2000', max_length=5, verbose_name='Serie Factura'),
        ),
    ]
