# Generated by Django 2.2.25 on 2021-12-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbai', '0005_auto_20211215_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='DatosFactura_Claves',
            field=models.CharField(choices=[('01', 'Régimen general'), ('02', 'Exportación'), ('03', 'Bienes usados, objectos de arte, antigüedades, colección'), ('04', 'Oro'), ('05', 'Agencias viajes'), ('06', ''), ('07', ''), ('08', ''), ('09', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', ''), ('51', ''), ('52', ''), ('53', '')], default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='DatosFactura_RetencionSoportada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Encadenamiento_FechaExpedicionFacturaAnterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Encadenamiento_NumFacturaAnterior',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Encadenamiento_SignatureValueFirmaFacturaAnterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Software_EntidadDesarrolladora_IDOtro_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Software_EntidadDesarrolladora_IDOtro_IDType',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Software_EntidadDesarrolladora_NIF',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='NIF Desarrollado'),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Software_LicenciaTBAI',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Software_Nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='HuellaTBAI_Software_Version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='TipoDesglose_BaseImponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=12, null=True, verbose_name='Base Imponible exenta IVA'),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='TipoDesglose_CausaExencion',
            field=models.CharField(blank=True, choices=[('E1', 'Artículo 20 Normal Foral del IVA'), ('E2', 'Artículo 21 Normal Foral del IVA'), ('E3', 'Artículo 22 Normal Foral del IVA'), ('E4', 'Artículo 23 y 24 Normal Foral del IVA'), ('E5', 'Artículo 25 Normal Foral del IVA'), ('E6', 'otra causa')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='TipoDesglose_Nosujeta_DetalleNoSujeta_Causa',
            field=models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=12, null=True, verbose_name='Importe no sujeto'),
        ),
        migrations.AddField(
            model_name='ticketbai_ticket',
            name='TipoDesglose_Nosujeta_DetalleNoSujeta_Importe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Base Imponible exenta IVA'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='DatosFactura_ImporteTotalFactura',
            field=models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=12, null=True, verbose_name='Importe Total'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Destinatarios_ApellidosNombreRazonSocial',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Razón Social Destinatario'),
        ),
        migrations.AlterField(
            model_name='ticketbai_ticket',
            name='Destinatarios_NIF',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='NIF Destinatario'),
        ),
    ]
