# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cambridge', '0002_auto_20160728_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='registration_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin de la matriculaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name=b'Fecha Nacm. DD-MM-AAAA'),
        ),
    ]
