# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cambridge', '0004_auto_20160728_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='registration_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin de la matriculaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='accept_conditions',
            field=models.BooleanField(default=True, help_text='You must accept the conditions to register', verbose_name='Acceptas las condiciones'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name=b'Fecha Nacm. DD-MM-AAAA'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='centre_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Centro'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='eide_alumn',
            field=models.BooleanField(default=b'False', help_text='Haz click en el check si eres alumno/a de EIDE. En caso contrario rellena porfavor la siguiente casilla.', verbose_name='Alumno EIDE'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagada'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='C\xf3digo Postal'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Tel\xe9fono'),
        ),
    ]
