# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cambridge', '0005_auto_20170406_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='registration_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin de la matriculaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name=b'Fecha Nacm. DD-MM-AAAA'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='C\xf3digo Postal'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Tel\xe9fono'),
        ),
    ]
