# Generated by Django 2.2.24 on 2021-11-13 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cambridge', '0009_auto_20210413_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Description')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('telephone', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cambridge.Level'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='accept_conditions',
            field=models.BooleanField(blank=True, default=True, verbose_name='He leído y acepto las condiciones generales.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='accept_photo_conditions',
            field=models.BooleanField(blank=True, default=True, help_text='Debes aceptar las condiciones de la la toma de foto para poder matricularte.', verbose_name='Doy mi consentimiento expreso para que mi imagen pueda ser utilizada en la página Web o en redes sociales del centro así como en todo el material publicitario que pueda utilizar.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='eide_alumn',
            field=models.BooleanField(blank=True, default='False', help_text='Haz click en el check si eres alumno/a de EIDE. En caso contrario rellena porfavor la siguiente casilla.', verbose_name='Alumno EIDE'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='exam',
            field=models.ForeignKey(limit_choices_to={'registration_end_date__gte': datetime.date(2021, 11, 13)}, on_delete=django.db.models.deletion.PROTECT, to='cambridge.Exam'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='minor',
            field=models.BooleanField(blank=True, default=False, verbose_name='El candidato es menor de edad y yo soy su padre/madre o tutor legal.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='schoolexam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cambridge.School'),
        ),
        migrations.AlterField(
            model_name='schoollevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cambridge.School'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='venueexam',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cambridge.Venue'),
        ),
        migrations.CreateModel(
            name='PrepCenterExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosting_venue', to='cambridge.PrepCenter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_exam', to='cambridge.Exam')),
            ],
        ),
    ]
