# Generated by Django 2.2.24 on 2021-11-20 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cambridge', '0010_auto_20211113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='prepcenter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Code Name'),
        ),
        migrations.AlterField(
            model_name='prepcenter',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='prepcenter',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='prepcenterexam',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_set', to='cambridge.PrepCenter'),
        ),
        migrations.AlterField(
            model_name='prepcenterexam',
            name='exam',
            field=models.ForeignKey(limit_choices_to={'registration_end_date__gte': datetime.date(2021, 11, 20)}, on_delete=django.db.models.deletion.PROTECT, related_name='center_set', to='cambridge.Exam'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='eide_alumn',
            field=models.BooleanField(blank=True, default='False', help_text='Haz click en el check si eres prepcenter/a de EIDE. En caso contrario rellena porfavor la siguiente casilla.', verbose_name='PrepCenter EIDE'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='exam',
            field=models.ForeignKey(limit_choices_to={'registration_end_date__gte': datetime.date(2021, 11, 20)}, on_delete=django.db.models.deletion.PROTECT, to='cambridge.Exam'),
        ),
        migrations.CreateModel(
            name='PrepCenterRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_set', to='cambridge.PrepCenter')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepcenterexam_set', to='cambridge.Registration')),
            ],
        ),
    ]
