# Generated by Django 2.2.24 on 2021-12-01 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import localflavor.es.models


class Migration(migrations.Migration):

    dependencies = [
        ('cambridge', '0011_auto_20211120_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='exam',
            field=models.ForeignKey(limit_choices_to={'registration_end_date__gte': datetime.date(2021, 12, 1)}, on_delete=django.db.models.deletion.PROTECT, to='cambridge.Exam'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='postal_code',
            field=localflavor.es.models.ESPostalCodeField(max_length=5, verbose_name='Código Postal'),
        ),
        migrations.DeleteModel(
            name='PrepCenterExam',
        ),
    ]
