# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-31 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneide', '0070_auto_20200517_1722'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_bool', models.BooleanField()),
                ('respuesta_texto', models.CharField(max_length=1000, verbose_name='Respuesta (1000carac. max.)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestioneide.Asistencia')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Consulta')),
            ],
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='confirmacion',
            name='respuesta_bool',
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='password',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='respuesta_choice',
            field=models.DecimalField(choices=[(1, 'S\xed'), (2, 'S\xed pero deseo otro horario'), (3, 'No')], decimal_places=0, default=0, max_digits=1, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='respuesta_texto',
            field=models.CharField(max_length=1000, verbose_name='Raz\xf3n (1000carac. max.)'),
        ),
    ]
