# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20200605_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacion',
            name='gestionada',
            field=models.BooleanField(default=False),
        ),
    ]
