# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_confirmacion_gestionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacion',
            name='respuesta_choice',
            field=models.DecimalField(choices=[(0, 'Sin contestar'), (1, 'S\xed'), (2, 'S\xed, pero deseo otro horario'), (3, 'No')], decimal_places=0, default=0, max_digits=1, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='respuesta_texto',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='OBSERVACIONES. Ind\xedquenos por favor su preferencia de horario, en caso de que quiera cambiar, o, si no va a asistir el curso que viene,  la raz\xf3n por la que no va a hacerlo.'),
        ),
    ]
