# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importar', '0002_olddatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='olddatabase',
            name='errors',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='olddatabase',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olddatabase',
            name='message',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
