# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaEide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('address', models.CharField(max_length=100, verbose_name='Direcci\xf3n')),
                ('location', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='C\xf3digo Postal')),
                ('sex', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha Nacm. DD-MM-AAAA')),
                ('telephone1', models.CharField(max_length=12, verbose_name='Segundo Tel\xe9fono Contacto')),
                ('email', models.EmailField(max_length=254)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accepta_condiciones', models.BooleanField(default=True, help_text='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.', verbose_name='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.')),
                ('nivel_ingles', models.CharField(default='', max_length=150, verbose_name='Estudios previos de ingles eNivel')),
                ('titulo_ingles', models.CharField(default='', max_length=150, verbose_name='Estudios previos de ingles eNivel')),
                ('clases_previas', models.CharField(default='', max_length=150, verbose_name='Estudios previos de ingles eNivel')),
            ],
        ),
    ]
