# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'matriculas', '0001_initial'), (b'matriculas', '0002_auto_20200517_1032')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaEide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direcci\xf3n')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('codigo_postal', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='C\xf3digo Postal')),
                ('sexo', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=254)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accepta_condiciones', models.BooleanField(help_text='Doy mi consentimiento expreso para recibir comunicaciones en \n        los t\xe9rminos anteriormente descritos.', verbose_name='Acepto las condiciones')),
                ('nivel_ingles', models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles eNivel')),
                ('titulo_ingles', models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles eNivel')),
                ('clases_previas', models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles eNivel')),
                ('apellido1', models.CharField(blank=True, default='', max_length=100, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now, help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha Nacimiento del alumno')),
                ('gestionada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('telefono1', models.CharField(default=666554433, max_length=12, verbose_name='Tel\xe9fono M\xf3vil de contacto')),
                ('telefono2', models.CharField(blank=True, default='', max_length=12, verbose_name='Segundo Tel\xe9fono Contacto')),
            ],
        ),
    ]
