# Generated by Django 2.2.24 on 2021-07-12 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(default='')),
                ('condiciones', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.DecimalField(choices=[(1, 'PB'), (2, 'CB'), (3, 'FS PB'), (4, 'FS CB'), (5, 'Linguaskill')], decimal_places=0, max_digits=1, verbose_name='Tipo Examen')),
                ('exam_date', models.DateField(default=django.utils.timezone.now)),
                ('registration_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin de la matriculación')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LinguaskillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaEide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6)),
                ('centro', models.DecimalField(choices=[(1, 'Santurce'), (2, 'Kabiezes'), (3, 'Sestao'), (4, 'Portugalete')], decimal_places=0, max_digits=1, verbose_name='Centro')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, default='', max_length=100, verbose_name='Segundo Apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('email', models.EmailField(help_text='Cuenta de correo principal, recibirá confirmación de esta matrícula', max_length=254, verbose_name='E-mail principal')),
                ('email2', models.EmailField(blank=True, default='', help_text='Otra cuenta de correo-e (opcional)', max_length=254, verbose_name='Segundo e-mail')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('codigo_postal', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Código Postal')),
                ('fecha_nacimiento', models.DateField(help_text='Formato: DD\\MM\\AAAA(día\\mes\x07ño)', verbose_name='Fecha Nacimiento del alumno')),
                ('telefono1', models.CharField(max_length=12, verbose_name='Teléfono Móvil de contacto')),
                ('telefono2', models.CharField(blank=True, default='', max_length=12, verbose_name='Segundo Teléfono Contacto')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('gestionada', models.BooleanField(default=False, verbose_name='Gestionada')),
                ('nivel_ingles', models.CharField(blank=True, default='', help_text='¿Conoce su nivel de ingles (A1/2,B1-1/1-2/2-1/2-2,C1)?', max_length=150, verbose_name='Nivel de ingles [opcional]')),
                ('titulo_ingles', models.CharField(blank=True, default='', help_text='¿Tiene alguna titulación de inglés? ¿Cuál? ¿Cuándo la obtuvo?', max_length=150, verbose_name='Títulación previa [opcional]')),
                ('clases_previas', models.CharField(blank=True, default='', help_text='¿Ha ido antes a una academia? ¿Puede decirnos el libro que utiliza/utilizaba?', max_length=150, verbose_name='Estudios previos de inglés [opcional]')),
                ('accepta_condiciones_imagen', models.BooleanField(help_text='Doy mi consentimiento expreso para que mi imagen pueda ser utilizada en la página \n        Web o en redes sociales del centro así como en todo el material publicitario que pueda utilizar, \n        en los términos anteriormente descritos', verbose_name='Acepto las condiciones')),
                ('accepta_condiciones_comunicacion', models.BooleanField(help_text='Doy mi consentimiento expreso para recibir comunicaciones en los términos anteriormente descritos.', verbose_name='Acepto las condiciones')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Description')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Description')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('location', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Código Postal')),
                ('sex', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-año)', verbose_name='Fecha Nacm. DD-MM-AAAA')),
                ('telephone', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
                ('eide_alumn', models.BooleanField(blank=True, default=False, help_text='Haz click en el check si eres alumno/a de EIDE. En caso contrario rellena porfavor la siguiente casilla.', verbose_name='Alumno EIDE')),
                ('centre_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Centro')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accept_conditions', models.BooleanField(blank=True, default=True, help_text='Doy mi consentimiento expreso para recibir comunicaciones en los términos anteriormente descritos.', verbose_name='Doy mi consentimiento expreso para recibir comunicaciones en los términos anteriormente descritos.')),
                ('accept_photo_conditions', models.BooleanField(blank=True, default=True, help_text='Debes aceptar las condiciones de la la toma de foto para poder matricularte.', verbose_name='Doy mi consentimiento expreso para que mi imagen pueda ser utilizada en la página Web o en redes sociales del centro así como en todo el material publicitario que pueda utilizar.')),
                ('minor', models.BooleanField(blank=True, default=False, verbose_name='El candidato es menor de edad y yo soy su padre/madre o tutor legal.')),
                ('tutor_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre de padre/madre o tutor.')),
                ('tutor_surname', models.CharField(blank=True, max_length=100, verbose_name='Apellido(s) del padre/madre o tutor.')),
                ('exam', models.ForeignKey(limit_choices_to={'registration_end_date__gte': datetime.date(2021, 7, 12)}, on_delete=django.db.models.deletion.CASCADE, to='matriculas.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaLinguaskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField(blank=True, help_text='Formato: DD-MM-AAAA(dia-mes-año)', verbose_name='Fecha propuesta DD-MM-AAAA')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('location', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Código Postal')),
                ('sex', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-año)', verbose_name='Fecha Nacm. DD-MM-AAAA')),
                ('telephone', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accept_conditions', models.BooleanField(blank=True, default=False, verbose_name='Acepto los términos y condiciones descritos a continuación ')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.LinguaskillLevel')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('location', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Código Postal')),
                ('sex', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-año)', verbose_name='Fecha Nacm. DD-MM-AAAA')),
                ('telephone', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accept_conditions', models.BooleanField(blank=True, default=False, verbose_name='Acepto los términos y condiciones descritos a continuación ')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='linguaskilllevel',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Venue'),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Level'),
        ),
        migrations.CreateModel(
            name='VenueExam',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculas.Exam')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Venue')),
            ],
            bases=('matriculas.exam',),
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('level_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculas.Level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.School')),
            ],
            bases=('matriculas.level',),
        ),
        migrations.CreateModel(
            name='SchoolExam',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculas.Exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.School')),
            ],
            bases=('matriculas.exam',),
        ),
    ]
