# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculaeide',
            old_name='postal_code',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='matriculaeide',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='matriculaeide',
            old_name='location',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='matriculaeide',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='matriculaeide',
            old_name='sex',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='matriculaeide',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='matriculaeide',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='matriculaeide',
            name='telephone1',
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='apellido1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha Nacimiento del alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='gestionada',
            field=models.BooleanField(default=False, verbose_name='Pagada'),
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='telefono1',
            field=models.CharField(default=666554433, max_length=12, verbose_name='Tel\xe9fono M\xf3vil de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='telefono2',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Segundo Tel\xe9fono Contacto'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='accepta_condiciones',
            field=models.BooleanField(help_text='Doy mi consentimiento expreso para recibir comunicaciones en \n        los t\xe9rminos anteriormente descritos.', verbose_name='Acepto las condiciones'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='clases_previas',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles eNivel'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='fecha_matricula',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='nivel_ingles',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles eNivel'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='titulo_ingles',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles eNivel'),
        ),
    ]
