# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_squashed_0002_auto_20200517_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaeide',
            name='apellido2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='apellido1',
            field=models.CharField(max_length=100, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha Nacimiento del alumno'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='telefono1',
            field=models.CharField(max_length=12, verbose_name='Tel\xe9fono M\xf3vil de contacto'),
        ),
    ]
