# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20200517_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaeide',
            name='sexo',
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='centro',
            field=models.DecimalField(choices=[(1, 'Santurce'), (2, 'Kabiezes'), (3, 'Sestao')], decimal_places=0, default=0, max_digits=1, verbose_name='Centro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='email2',
            field=models.EmailField(blank=True, default='', help_text='Otra cuenta de correo-e (opcional)', max_length=254, verbose_name='Segundo e-mail'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='clases_previas',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Estudios previos de ingles'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Direcci\xf3n de correo-e'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='nivel_ingles',
            field=models.CharField(blank=True, default='', help_text='\xbfHa ido antes a una academia? \xbfPuedes decirnos el libro que utiliza/utilizaba?', max_length=150, verbose_name='Estudios previos de ingles'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='titulo_ingles',
            field=models.CharField(blank=True, default='', help_text='\xbfTiene alguna titulaci\xf3n de ingl\xe9s? \xbfCu\xe1l? \xbfCu\xe1ndo la obtuvo?', max_length=150, verbose_name='T\xedtulaci\xf3n previa'),
        ),
    ]
