# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_auto_20200521_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaeide',
            name='accepta_condiciones',
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='accepta_condiciones_comunicacion',
            field=models.BooleanField(default=False, help_text='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.', verbose_name='Acepto las condiciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matriculaeide',
            name='accepta_condiciones_imagen',
            field=models.BooleanField(default=False, help_text='Doy mi consentimiento expreso para que mi imagen pueda ser utilizada en la p\xe1gina \n        Web o en redes sociales del centro as\xed como en todo el material publicitario que pueda utilizar, \n        en los t\xe9rminos anteriormente descritos', verbose_name='Acepto las condiciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='clases_previas',
            field=models.CharField(blank=True, default='', help_text='\xbfHa ido antes a una academia? \xbfPuedes decirnos el libro que utiliza/utilizaba?', max_length=150, verbose_name='Estudios previos de ingles [opcional]'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='email',
            field=models.EmailField(help_text='Cuenta de correo principal, recibir\xe1 confirmaci\xf3n de esta matr\xedcula', max_length=254, verbose_name='E-mail principal'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Formato: DD\\MM\\AAAA(d\xeda\\mes\x07\xf1o)', verbose_name='Fecha Nacimiento del alumno'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='nivel_ingles',
            field=models.CharField(blank=True, default='', help_text='\xbfConoce su nivel de ingles (A1/2,B1-1/1-2/2-1/2-2,C1)?', max_length=150, verbose_name='Nivel de ingles [opcional]'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='titulo_ingles',
            field=models.CharField(blank=True, default='', help_text='\xbfTiene alguna titulaci\xf3n de ingl\xe9s? \xbfCu\xe1l? \xbfCu\xe1ndo la obtuvo?', max_length=150, verbose_name='T\xedtulaci\xf3n previa [opcional]'),
        ),
    ]
