# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_matriculaeide_alumno_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinguaskillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaLinguaskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha propuesta DD-MM-AAAA')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('address', models.CharField(max_length=100, verbose_name='Direcci\xf3n')),
                ('location', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='C\xf3digo Postal')),
                ('sex', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha Nacm. DD-MM-AAAA')),
                ('telephone', models.CharField(max_length=12, verbose_name='Tel\xe9fono')),
                ('email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accept_conditions', models.BooleanField(default=True, help_text='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.', verbose_name='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.LinguaskillLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Description')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='clases_previas',
            field=models.CharField(blank=True, default='', help_text='\xbfHa ido antes a una academia? \xbfPuede decirnos el libro que utiliza/utilizaba?', max_length=150, verbose_name='Estudios previos de ingl\xe9s [opcional]'),
        ),
        migrations.AlterField(
            model_name='matriculaeide',
            name='gestionada',
            field=models.BooleanField(default=False, verbose_name='Gestionada'),
        ),
        migrations.AddField(
            model_name='linguaskilllevel',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Venue'),
        ),
    ]
