# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-11-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_auto_20200708_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.DecimalField(choices=[(1, 'PB'), (2, 'CB'), (3, 'FS PB'), (4, 'FS CB'), (5, 'Linguaskill')], decimal_places=0, max_digits=1, verbose_name='Tipo Examen')),
                ('exam_date', models.DateField(default=django.utils.timezone.now)),
                ('registration_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha fin de la matriculaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Password')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('address', models.CharField(max_length=100, verbose_name='Direcci\xf3n')),
                ('location', models.CharField(max_length=100, verbose_name='Localidad')),
                ('postal_code', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='C\xf3digo Postal')),
                ('sex', models.DecimalField(choices=[(1, 'Male'), (2, 'Female')], decimal_places=0, max_digits=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha Nacm. DD-MM-AAAA')),
                ('telephone', models.CharField(max_length=12, verbose_name='Tel\xe9fono')),
                ('email', models.EmailField(max_length=254)),
                ('eide_alumn', models.BooleanField(default='False', help_text='Haz click en el check si eres alumno/a de EIDE. En caso contrario rellena porfavor la siguiente casilla.', verbose_name='Alumno EIDE')),
                ('centre_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Centro')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('accept_conditions', models.BooleanField(default=True, help_text='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.', verbose_name='Doy mi consentimiento expreso para recibir comunicaciones en los t\xe9rminos anteriormente descritos.')),
                ('accept_photo_conditions', models.BooleanField(default=True, help_text='Debes aceptar las condiciones de la la toma de foto para poder matricularte.', verbose_name='Doy mi consentimiento expreso para que mi imagen pueda ser utilizada en la p\xe1gina Web o en redes sociales del centro as\xed como en todo el material publicitario que pueda utilizar.')),
                ('minor', models.BooleanField(default=False, verbose_name='El candidato es menor de edad y yo soy su padre/madre o tutor legal.')),
                ('tutor_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre de padre/madre o tutor.')),
                ('tutor_surname', models.CharField(blank=True, max_length=100, verbose_name='Apellido(s) del padre/madre o tutor.')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Description')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='matriculalinguaskill',
            name='accept_conditions',
            field=models.BooleanField(default=False, verbose_name='Acepto los t\xe9rminos y condiciones descritos a continuaci\xf3n '),
        ),
        migrations.AlterField(
            model_name='matriculalinguaskill',
            name='proposed_date',
            field=models.DateField(blank=True, help_text='Formato: DD-MM-AAAA(dia-mes-a\xf1o)', verbose_name='Fecha propuesta DD-MM-AAAA'),
        ),
        migrations.CreateModel(
            name='SchoolExam',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculas.Exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.School')),
            ],
            bases=('matriculas.exam',),
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('level_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculas.Level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.School')),
            ],
            bases=('matriculas.level',),
        ),
        migrations.CreateModel(
            name='VenueExam',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculas.Exam')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Venue')),
            ],
            bases=('matriculas.exam',),
        ),
        migrations.AddField(
            model_name='registration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.Level'),
        ),
    ]
