# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_curso_matriculacurso_squashed_0009_curso_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
