# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_auto_20210219_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaeide',
            name='centro',
            field=models.DecimalField(choices=[(1, 'Santurce'), (2, 'Kabiezes'), (3, 'Sestao'), (4, 'Portugalete')], decimal_places=0, max_digits=1, verbose_name='Centro'),
        ),
    ]
