# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20190106_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='titulo',
            field=models.CharField(max_length=125),
        ),
    ]
